language: java
sudo: true
jdk:
- oraclejdk8
dist: trusty
deploy:
  provider: s3
  access_key_id: AKIAZDOLGS7LXBQAN3Z2
  secret_access_key:
    secure: tNPIH+GVp5kSlATxEqyxO78wdvTlWOa9hM8wLu6IwYundeAke49SwWGD7Xy8d1LhiRhiSDypUFmwtYJkDfTUFMLOGlks44URNvJ8GwCRkYlTA9hXcjSwU8nzgCgSB/AE6chGd0EK6jX5NCrx8ZVN4cUIzndQzPajfgedwYQnT02M9JaOi1NqZjZyxzzN7sMKR9SmBqP2FL8mmmkujxFJ9Gc9afmKIa/yh8ZpKxZ398+SQP1bkhuuyPa2JAVSjEp94s5prG0jaGNBXphGQdLrPY0r4cC10KosPy27glavAom5y4cOPQFdGKU8GTPZwUoOMVndVD+NtNyIS/oA44KMK5xZHlmJpRCHqhkIXjtzze/gMXFzgEWdVqVgA1eBOXEyZM1GDqpqSNIQHf6hDY3phWpH63IpLmM8ZYIXqFo+cAmZYm6q1cezcnkqUM62pThdgwFl4rjuQYfXJmYa8sFbIhIQK7vCfjrp2sweMfdM9TgwTZZESP1XJLcdtxpbD0H75mR6gUxbPmJmAuuEH3+gq96ZvDM2DP2SDos2a9YeRQK2qdkhHSWihIM8LGNTO0K+4iAi1w1tn1dOMjaFSr3HdtnGShYue3qU9++71HMirKYwPVY/OHbgIdG7iOhoY/5VLH/WmixR5nmgLDNp0rqTRzA2IwRneG6wIB0rUXohMLg=
  bucket: repo-lambda-functions
  skip_cleanup: true
