language: java
sudo: true
jdk:
- oraclejdk8
dist: trusty
before_deploy:
  - chmod +x mvnw
  - cd /home/travis/build/juli0mendes/user-crud/target/
  - mkdir deploy_directory
  - chmod +x mvnw deploy_directory
  - chmod +x mvnw user-crud-1.0.0.jar
  - mv user-crud-1.0.0.jar /deploy_directory
deploy:
  provider: s3
  access_key_id: AKIAZDOLGS7LXBQAN3Z2
  secret_access_key:
    secure: pByPyrDy/O0vxua7okQw5k2myBt1Ngy7LvyaQrNhdRx0AOOzE0wilw/1FcXP1Ols91X5SwEfJUcohmU07PU/qx29CiWf8RFcdyXf/ZzAp7d2a+z0J2J8Heh/3nEJpqTu+lccIh8uxq3oL6ETkixPLgOdHWSODQJHpWlprezGna3GGy4mXAfi4coWEYmYCGOmgt1ryLG+b0gn/epiI6JKJ1f7BZa3OgLPlNVpxa/kvDM9sYN0RnmBtxDNV8z0Wa2xUvE9nztj/64W2TmO7O54ZW6SAoua/NSXwmUjpKkF8SGKfuBX41QYG8Z1jqmEBumc8ZYbxP7e7RYNMXnTUeaWFOB7f1efuBIN6e7PeNhvGEhi5vso22L2qeD+0DkMFOEv2cYL8kOhjAhMffa5g973Pzs7Hnuim6NzGH/BTkX6bVhqMlDMoSlx7pr1PzJaDsCrsKPUIUoZMvM3R7VjDFDC73em8XHNF1jkdlmn9e1AK89MtbKlNunmYsTDZTCkzrMPxIuQIeWmzfLngNecvp7xGuXjkegkTeIK7O/zbmu1WgJOhx/+5OtOTnsq7tXDUqJgRkcUKeuNjJzVY7ftwObRzLp2hpGB2ysSavpVp4Cu6yk2Fgp7E/mWLi9M3BVjCKbC97GNSgaOhkWe54IPuwlzj4TzhNJKxEbiX7ZTPGGMbkE=
  bucket: repo-lambda-functions
  skip_cleanup: true
  local-dir: /home/travis/build/juli0mendes/user-crud/target/deploy_directory