language: java
sudo: true
jdk:
  - oraclejdk8
dist: trusty
deploy:
  provider: s3
  access_key_id: "AKIAZDOLGS7LZJAHZMEN"
  secret_access_key: "error_key"
  bucket: "repo-lambda-functions"
  skip_cleanup: true